from __future__ import annotations

from enum import Enum


class BotState(str, Enum):
    BOOTING = "BOOTING"
    CONFIG_CHECK = "CONFIG_CHECK"
    VAULT_CHECK = "VAULT_CHECK"
    API_PERMISSION_CHECK = "API_PERMISSION_CHECK"
    PAPER_READY = "PAPER_READY"
    SANDBOX_READY = "SANDBOX_READY"
    LIVE_BLOCKED = "LIVE_BLOCKED"
    RUNNING = "RUNNING"
    DEGRADED = "DEGRADED"
    SHUTDOWN_REQUESTED = "SHUTDOWN_REQUESTED"
    SAFELY_STOPPED = "SAFELY_STOPPED"
    EMERGENCY_STOPPED = "EMERGENCY_STOPPED"
    ERROR = "ERROR"
